version: '3'
services:
  telcotools-web:
    container_name: telcotools-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./src:/usr/src/telcotoolsapi/src
      - ./scripts:/usr/src/telcotoolsapi/scripts
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
